spring.application.name=rate-printer
server.port=0

grpc.client.deadline-millis=3000
rate.provider.service-name=currency-rate-provider

spring.cloud.zookeeper.connect-string=localhost:2181
spring.cloud.zookeeper.discovery.root=/services
spring.cloud.zookeeper.discovery.register=false

rate.base-currency=USD
rate.quote-currency=RUB
rate.poll-interval=5000

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.access=unrestricted
management.endpoint.health.access=unrestricted
management.endpoints.access.default=unrestricted
management.server.port=8082
management.metrics.tags.application=${spring.application.name}
