spring.application.name=currency-rate-provider

grpc.server.port=50051

spring.cloud.zookeeper.connect-string=localhost:2181
spring.cloud.zookeeper.discovery.root=/services
spring.cloud.zookeeper.discovery.register=true
spring.cloud.zookeeper.discovery.instance-port=${grpc.server.port}
spring.cloud.service-registry.auto-registration.enabled=false

rate.base-value=90.0
rate.spread=1.0

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.access=unrestricted
management.endpoint.health.access=unrestricted
management.endpoints.access.default=unrestricted
management.server.port=8081

